name: nexthour
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_pro: ^0.0.13
  http: ^0.12.0+4
  path_provider: ^1.6.8
  validate: ^1.7.0
  connectivity: ^0.4.8+6
  flutter_swiper: ^1.1.4
  flutube: ^0.7.3
  bubble_tab_indicator: ^0.1.4
  shimmer: ^1.0.0
  sticky_headers: ^0.1.8
  fluttertoast: ^3.1.3
  flutter_html: ^0.10.4
  intro_slider: ^2.2.5
  webview_flutter: ^0.3.19+5
  font_awesome_flutter: ^8.5.0
  flutter_datetime_picker: 1.2.6
  image_picker: 0.6.1+2
  launch_review: 2.0.0
  share: 0.6.2+1
  stripe_api: ^1.1.0
  intl: ^0.15.8
  charts_flutter: ^0.5.0
  flutter_credit_card:
  onesignal_flutter: ^2.3.2
  shared_preferences: ^0.5.7+2
  braintree_payment: ^1.2.2
  dio: ^3.0.9
  video_player: ^0.10.11
  wakelock: 0.1.3+3
  open_iconic_flutter: ^0.3.0
  screen: ^0.0.5
  sqflite: ^1.2.1
  permission_handler: ^4.0.0
  flutter_downloader: ^1.4.1
  data_connection_checker: ^0.3.4

  cupertino_icons: ^0.1.2
  flutter_paystack: 1.0.1
  razorpay_flutter: ^1.2.1
#  paytm: ^1.0.0
  auto_size_text: ^2.1.0
  flutter_custom_clippers: ^1.1.0
  rating_bar: ^0.2.0
  get_ip: ^0.4.0
  device_info: ^0.4.2+4
  flutter_facebook_login: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/
    - icons/

